# Generated by Django 5.2.9 on 2026-01-04 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('blocked_words', models.TextField(blank=True, help_text='Слова для блокировки, каждое с новой строки')),
                ('max_messages_per_minute', models.PositiveIntegerField(default=10, help_text='Максимальное количество сообщений в минуту от одного пользователя')),
                ('enable_toxicity_filter', models.BooleanField(default=False, help_text='Включить фильтр токсичности')),
            ],
            options={
                'verbose_name': 'Настройка модерации',
                'verbose_name_plural': 'Настройки модерации',
            },
        ),
        migrations.CreateModel(
            name='UserMessageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Частота сообщений пользователя',
                'verbose_name_plural': 'Частоты сообщений пользователей',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_moderated', '-created_at'], name='blog_messag_is_mode_7c3971_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_blocked', '-created_at'], name='blog_messag_is_bloc_868998_idx'),
        ),
        migrations.AddField(
            model_name='moderationsettings',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_settings', to='blog.chatroom'),
        ),
        migrations.AddField(
            model_name='usermessagerate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.chatroom'),
        ),
        migrations.AddField(
            model_name='usermessagerate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usermessagerate',
            index=models.Index(fields=['user', 'room', '-timestamp'], name='blog_userme_user_id_95b966_idx'),
        ),
    ]
