# Generated by Django 5.2.9 on 2026-01-04 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_moderationsettings_usermessagerate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Причина бана', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Время окончания бана (если null - бан постоянный)', null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='blog.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бан пользователя',
                'verbose_name_plural': 'Баны пользователей',
                'indexes': [models.Index(fields=['user', 'is_active'], name='blog_userba_user_id_ce2c7a_idx'), models.Index(fields=['expires_at'], name='blog_userba_expires_fc3efc_idx')],
            },
        ),
    ]
