# Generated by Django 5.2.9 on 2026-01-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userban',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Время окончания бана (если null - бан постоянный)', null=True, verbose_name='Окончание бана'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Постоянный бан'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='reason',
            field=models.CharField(help_text='Причина бана', max_length=500, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='blog.chatroom', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
